name: PlayedTime
version: 1.0
api: 3.0.0
main: PlayedTime\Renall\Main
author: Renall

commands:
  playedtime:
    description: "Spawn Leaderboard"
    default: op
    permissions: playedtime.spawn
    
permissions:
    playedtime.spawn:
        default: op
        description: "Permissions For Spawn Floating Leaderboard"